from __future__ import annotations

from dataclasses import dataclass
import math

import numpy as np
from scipy.integrate import cumulative_trapezoid
from scipy.linalg import eigh

from .atom import configuration_string, electron_configuration

_L_BY_LETTER = {"s": 0, "p": 1, "d": 2}

# Squared Wigner 3j coefficients (l_a l_b k; 0 0 0)^2 for l<=2.
# Hard-coded to keep the runtime NumPy/SciPy-only.
_W3J_SQ: dict[tuple[int, int], dict[int, float]] = {
    (0, 0): {0: 1.0},
    (0, 1): {1: 1.0 / 3.0},
    (1, 0): {1: 1.0 / 3.0},
    (0, 2): {2: 1.0 / 5.0},
    (2, 0): {2: 1.0 / 5.0},
    (1, 1): {0: 1.0 / 3.0, 2: 2.0 / 15.0},
    (1, 2): {1: 2.0 / 15.0, 3: 3.0 / 35.0},
    (2, 1): {1: 2.0 / 15.0, 3: 3.0 / 35.0},
    (2, 2): {0: 1.0 / 5.0, 2: 2.0 / 35.0, 4: 2.0 / 35.0},
}


@dataclass(frozen=True)
class Subshell:
    label: str
    n: int
    l: int
    occupancy: int
    alpha_occupancy: int
    beta_occupancy: int


@dataclass(frozen=True)
class AverageAtomicHFResult:
    z: int
    charge: int
    electron_count: int
    configuration: str
    basis_size: int
    grid_points: int
    iterations: int
    converged: bool
    energy_hartree: float
    kinetic_hartree: float
    nuclear_attraction_hartree: float
    direct_hartree: float
    exchange_hartree: float
    virial_residual_hartree: float
    target_s: float
    target_s2: float
    channel_summary: tuple[dict, ...]

    @property
    def electron_electron_hartree(self) -> float:
        return self.direct_hartree + self.exchange_hartree

    def as_dict(self) -> dict:
        return {
            "schema": "RESCHEM_ATOMIC_AVERAGE_HF_V0_1",
            "Z": self.z,
            "charge": self.charge,
            "electron_count": self.electron_count,
            "configuration": self.configuration,
            "basis_size": self.basis_size,
            "grid_points": self.grid_points,
            "iterations": self.iterations,
            "converged": self.converged,
            "energy_hartree": self.energy_hartree,
            "components_hartree": {
                "kinetic": self.kinetic_hartree,
                "nuclear_attraction": self.nuclear_attraction_hartree,
                "direct": self.direct_hartree,
                "exchange": self.exchange_hartree,
                "electron_electron": self.electron_electron_hartree,
            },
            "virial_residual_hartree": self.virial_residual_hartree,
            "target_spin": {"S": self.target_s, "S2": self.target_s2},
            "channels": list(self.channel_summary),
            "method": (
                "spherically averaged configuration unrestricted Hartree-Fock; "
                "Slater radial basis; nonlocal multipole exchange through l<=2"
            ),
            "scope": (
                "control solver for configurations generated by reschem.atom through Kr; "
                "open shells are configuration-averaged rather than term-resolved"
            ),
            "tir_status": "NOT_APPLIED_CONTROL_BASELINE",
            "affective_status": "NOT_APPLIED_CONTROL_BASELINE",
            "epistemic_status": "IMPLEMENTED_NUMERICAL_CONTROL_MODEL",
        }


def subshells_for_atom(z: int, charge: int = 0) -> tuple[Subshell, ...]:
    configuration = electron_configuration(z, charge)
    out: list[Subshell] = []
    for label, occupancy in configuration.items():
        n = int(label[0])
        try:
            l = _L_BY_LETTER[label[1]]
        except KeyError as exc:
            raise ValueError(f"unsupported subshell in v0.1 average HF: {label}") from exc
        m_capacity = 2 * l + 1
        alpha = min(occupancy, m_capacity)
        beta = max(0, occupancy - m_capacity)
        out.append(Subshell(label, n, l, occupancy, alpha, beta))
    return tuple(out)


def _trap_weights(x: np.ndarray) -> np.ndarray:
    w = np.empty_like(x)
    w[0] = 0.5 * (x[1] - x[0])
    w[-1] = 0.5 * (x[-1] - x[-2])
    w[1:-1] = 0.5 * (x[2:] - x[:-2])
    return w


def _basis_norms(l: int, zetas: np.ndarray) -> np.ndarray:
    return (2.0 * zetas) ** (l + 1.5) / math.sqrt(math.gamma(2 * l + 3))


def _eval_slater_basis(l: int, zetas: np.ndarray, r: np.ndarray) -> np.ndarray:
    norms = _basis_norms(l, zetas)
    return r[:, None] ** (l + 1) * np.exp(-r[:, None] * zetas[None, :]) * norms[None, :]


def _analytic_radial_matrices(l: int, nuclear_charge: int, zetas: np.ndarray):
    norms = _basis_norms(l, zetas)
    size = zetas.size
    overlap = np.empty((size, size), dtype=float)
    kinetic = np.empty_like(overlap)
    nuclear = np.empty_like(overlap)
    for i, zi in enumerate(zetas):
        for j, zj in enumerate(zetas):
            a = zi + zj
            prefactor = norms[i] * norms[j]
            i0 = math.gamma(2 * l + 1) / a ** (2 * l + 1)
            i1 = math.gamma(2 * l + 2) / a ** (2 * l + 2)
            i2 = math.gamma(2 * l + 3) / a ** (2 * l + 3)
            overlap[i, j] = prefactor * i2
            kinetic[i, j] = 0.5 * prefactor * (
                (l + 1) ** 2 * i0
                - (l + 1) * (zi + zj) * i1
                + zi * zj * i2
                + l * (l + 1) * i0
            )
            nuclear[i, j] = -float(nuclear_charge) * prefactor * i1
    return overlap, kinetic, nuclear, kinetic + nuclear


def _radial_kernel_apply(g: np.ndarray, r: np.ndarray, multipole_k: int) -> np.ndarray:
    inside = cumulative_trapezoid((r[:, None] ** multipole_k) * g, r, axis=0, initial=0.0)
    reverse_tail = cumulative_trapezoid(
        (g / r[:, None] ** (multipole_k + 1))[::-1], r[::-1], axis=0, initial=0.0
    )
    tail = -reverse_tail[::-1]
    return inside / r[:, None] ** (multipole_k + 1) + (r[:, None] ** multipole_k) * tail


def _direct_potential(radial_density: np.ndarray, r: np.ndarray) -> np.ndarray:
    inside = cumulative_trapezoid(radial_density, r, initial=0.0)
    reverse_tail = cumulative_trapezoid((radial_density / r)[::-1], r[::-1], initial=0.0)
    tail = -reverse_tail[::-1]
    return inside / r + tail


def _local_matrix(basis: np.ndarray, potential: np.ndarray, weights: np.ndarray) -> np.ndarray:
    matrix = basis.T @ ((weights * potential)[:, None] * basis)
    return 0.5 * (matrix + matrix.T)


def _exchange_matrix(target_basis, source_orbital, r, weights, multipole_k):
    products = source_orbital[:, None] * target_basis
    transformed = _radial_kernel_apply(products, r, multipole_k)
    matrix = target_basis.T @ (weights[:, None] * source_orbital[:, None] * transformed)
    return 0.5 * (matrix + matrix.T)


def _orthonormalize_columns(coefficients: np.ndarray, overlap: np.ndarray) -> np.ndarray:
    metric = coefficients.T @ overlap @ coefficients
    values, vectors = np.linalg.eigh(metric)
    if np.min(values) <= 0.0:
        raise FloatingPointError("non-positive orbital overlap metric")
    return coefficients @ vectors @ np.diag(1.0 / np.sqrt(values)) @ vectors.T


def solve_atom_average_hf(
    z: int,
    charge: int = 0,
    *,
    basis_size: int = 22,
    grid_points: int = 1400,
    zeta_min: float = 0.02,
    radial_grid_max_bohr: float = 120.0,
    mixing: float = 0.32,
    max_iterations: int = 100,
    tolerance_hartree: float = 5e-8,
) -> AverageAtomicHFResult:
    """Spherical average-of-configuration atomic HF control solver.

    Configuration comes directly from reschem.atom. Exchange is nonlocal and
    keeps the exact l<=2 angular multipoles. Open shells are averaged over m,
    so term-specific splittings are intentionally outside v0.1. TIR and
    affective semantics are absent by construction.
    """
    if basis_size < 12:
        raise ValueError("basis_size must be >= 12")
    if grid_points < 500:
        raise ValueError("grid_points must be >= 500")
    if zeta_min <= 0.0:
        raise ValueError("zeta_min must be positive")
    if radial_grid_max_bohr <= 0.0:
        raise ValueError("radial_grid_max_bohr must be positive")
    if not (0.0 < mixing <= 1.0):
        raise ValueError("mixing must be in (0,1]")

    subshells = subshells_for_atom(z, charge)
    electron_count = sum(shell.occupancy for shell in subshells)
    if electron_count <= 0:
        raise ValueError("v0.1 average HF requires at least one electron")

    active_l = sorted({shell.l for shell in subshells})
    zetas = np.geomspace(zeta_min, max(20.0, 4.0 * z), basis_size)
    r = np.geomspace(1e-8, radial_grid_max_bohr, grid_points)
    weights = _trap_weights(r)

    overlap = {}
    kinetic = {}
    nuclear = {}
    one_body = {}
    basis = {}
    for l in active_l:
        overlap[l], kinetic[l], nuclear[l], one_body[l] = _analytic_radial_matrices(l, z, zetas)
        basis[l] = _eval_slater_basis(l, zetas, r)

    occupation = {}
    orbitals = {}
    for l in active_l:
        highest_index = max(shell.n - l - 1 for shell in subshells if shell.l == l)
        _, vectors = eigh(one_body[l], overlap[l], subset_by_index=[0, highest_index], check_finite=False)
        for shell in subshells:
            if shell.l != l:
                continue
            index = shell.n - l - 1
            if shell.alpha_occupancy:
                key = (shell.n, l, "alpha")
                occupation[key] = shell.alpha_occupancy
                orbitals[key] = vectors[:, index].copy()
            if shell.beta_occupancy:
                key = (shell.n, l, "beta")
                occupation[key] = shell.beta_occupancy
                orbitals[key] = vectors[:, index].copy()

    def radial_orbital(key):
        return basis[key[1]] @ orbitals[key]

    def energy_components():
        density = np.zeros_like(r)
        cache = {}
        kinetic_energy = 0.0
        nuclear_energy = 0.0
        for key, count in occupation.items():
            u = radial_orbital(key)
            cache[key] = u
            density += count * u * u
            l = key[1]
            c = orbitals[key]
            kinetic_energy += count * float(c @ kinetic[l] @ c)
            nuclear_energy += count * float(c @ nuclear[l] @ c)
        direct_potential = _direct_potential(density, r)
        direct_energy = 0.5 * float(np.sum(weights * density * direct_potential))
        exchange_energy = 0.0
        for key_a, count_a in occupation.items():
            _, l_a, spin_a = key_a
            u_a = cache[key_a]
            for key_b, count_b in occupation.items():
                _, l_b, spin_b = key_b
                if spin_a != spin_b:
                    continue
                product = u_a * cache[key_b]
                for multipole_k, angular in _W3J_SQ[(l_a, l_b)].items():
                    transformed = _radial_kernel_apply(product[:, None], r, multipole_k)[:, 0]
                    exchange_energy -= 0.5 * count_a * count_b * angular * float(
                        np.sum(weights * product * transformed)
                    )
        total = kinetic_energy + nuclear_energy + direct_energy + exchange_energy
        return total, kinetic_energy, nuclear_energy, direct_energy, exchange_energy

    previous_energy = None
    converged = False
    for iteration in range(1, max_iterations + 1):
        density = np.zeros_like(r)
        orbital_cache = {}
        for key, count in occupation.items():
            u = radial_orbital(key)
            orbital_cache[key] = u
            density += count * u * u
        direct_potential = _direct_potential(density, r)
        updated = {}

        for l in active_l:
            direct_matrix = _local_matrix(basis[l], direct_potential, weights)
            for spin in ("alpha", "beta"):
                targets = sorted(key for key in occupation if key[1] == l and key[2] == spin)
                if not targets:
                    continue
                exchange = np.zeros_like(one_body[l])
                for source_key, source_count in occupation.items():
                    _, source_l, source_spin = source_key
                    if source_spin != spin:
                        continue
                    source = orbital_cache[source_key]
                    for multipole_k, angular in _W3J_SQ[(l, source_l)].items():
                        exchange += source_count * angular * _exchange_matrix(
                            basis[l], source, r, weights, multipole_k
                        )
                fock = one_body[l] + direct_matrix - exchange
                highest_index = max(key[0] - l - 1 for key in targets)
                _, vectors = eigh(fock, overlap[l], subset_by_index=[0, highest_index], check_finite=False)
                candidate = np.column_stack([vectors[:, key[0] - l - 1] for key in targets])
                current = np.column_stack([orbitals[key] for key in targets])
                for column in range(candidate.shape[1]):
                    if float(current[:, column] @ overlap[l] @ candidate[:, column]) < 0.0:
                        candidate[:, column] *= -1.0
                mixed = _orthonormalize_columns(
                    (1.0 - mixing) * current + mixing * candidate, overlap[l]
                )
                for column, key in enumerate(targets):
                    updated[key] = mixed[:, column]

        orbitals.update(updated)
        total, _, _, _, _ = energy_components()
        if previous_energy is not None and abs(total - previous_energy) < tolerance_hartree:
            converged = True
            break
        previous_energy = total

    total, kinetic_energy, nuclear_energy, direct_energy, exchange_energy = energy_components()
    n_alpha = sum(count for key, count in occupation.items() if key[2] == "alpha")
    n_beta = sum(count for key, count in occupation.items() if key[2] == "beta")
    target_s = 0.5 * (n_alpha - n_beta)

    channels = []
    for shell in subshells:
        item = {
            "subshell": shell.label,
            "n": shell.n,
            "l": shell.l,
            "occupancy": shell.occupancy,
            "alpha_occupancy": shell.alpha_occupancy,
            "beta_occupancy": shell.beta_occupancy,
        }
        spin_channels = {}
        for spin in ("alpha", "beta"):
            key = (shell.n, shell.l, spin)
            if key not in orbitals:
                continue
            u = radial_orbital(key)
            mean_r = float(np.sum(weights * r * u * u))
            mean_r2 = float(np.sum(weights * r * r * u * u))
            spin_channels[spin] = {
                "mean_radius_bohr": mean_r,
                "radial_sigma_bohr": math.sqrt(max(0.0, mean_r2 - mean_r * mean_r)),
            }
        item["radial_channels"] = spin_channels
        channels.append(item)

    return AverageAtomicHFResult(
        z=z,
        charge=charge,
        electron_count=electron_count,
        configuration=configuration_string(electron_configuration(z, charge)),
        basis_size=basis_size,
        grid_points=grid_points,
        iterations=iteration,
        converged=converged,
        energy_hartree=total,
        kinetic_hartree=kinetic_energy,
        nuclear_attraction_hartree=nuclear_energy,
        direct_hartree=direct_energy,
        exchange_hartree=exchange_energy,
        virial_residual_hartree=2.0 * kinetic_energy + nuclear_energy + direct_energy + exchange_energy,
        target_s=target_s,
        target_s2=target_s * (target_s + 1.0),
        channel_summary=tuple(channels),
    )


def solve_h_to_ne_blind(*, basis_size: int = 18, grid_points: int = 1000, **kwargs):
    return tuple(
        solve_atom_average_hf(z, basis_size=basis_size, grid_points=grid_points, **kwargs)
        for z in range(1, 11)
    )
