"""Discrete coordination/reorganization ladder for heavier main-group centres.

This v0.5 candidate is motivated by the explicit v0.3 falsifiers PCl5 and SF6.
It does not alter the frozen ground-state shell relation degree d0.

For an outer s/p shell with occupation v and closed-shell capacity C,

    d0 = min(v, C-v)
    d* = max(v, C-v).

For heavier main-group centres on the above-half branch (v > C/2, principal
n >= 3), candidate coordination states are generated by discrete pair
activation steps

    d_q = d0 + 2 q,

up to d*.  q is a representation-level reorganization index.  It is not an
oxidation state, an excited-state quantum number, a d-orbital occupation, or
an energetic prediction.

Second-period centres are deliberately not expanded in v0.5, and closed-shell
centres remain inactive.  This is a fail-closed modelling choice that must be
tested independently rather than treated as established chemistry.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass

from .atom import ELEMENT_SYMBOLS
from .compound_shell_relations import valence_shell_profile


@dataclass(frozen=True)
class CoordinationState:
    Z: int
    symbol: str
    q: int
    relation_degree: int
    base_relation_degree: int
    dual_relation_degree: int
    principal_n: int
    outer_sp_electrons: int
    closed_shell_capacity: int
    branch: str
    status: str

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass(frozen=True)
class MonovalentCoordinationCandidate:
    centre_Z: int
    centre_symbol: str
    ligand_Z: int
    ligand_symbol: str
    q: int
    centre_relation_degree: int
    ligand_count: int
    empirical_formula: str
    status: str = "MODEL_DEFINED_COORDINATION_REORGANIZATION_CANDIDATE"

    def to_dict(self) -> dict:
        return asdict(self)


def coordination_ladder(z: int) -> tuple[CoordinationState, ...]:
    """Return the discrete candidate coordination states for one centre."""
    profile = valence_shell_profile(z)
    base = profile.relation_degree
    dual = max(profile.outer_sp_electrons, profile.holes_to_closed_shell)

    if base == 0:
        return (
            CoordinationState(
                Z=z,
                symbol=profile.symbol,
                q=0,
                relation_degree=0,
                base_relation_degree=0,
                dual_relation_degree=dual,
                principal_n=profile.principal_n,
                outer_sp_electrons=profile.outer_sp_electrons,
                closed_shell_capacity=profile.closed_shell_capacity,
                branch="CLOSED_UNACTIVATED",
                status="CLOSED_SHELL_FAIL_CLOSED_V0_5",
            ),
        )

    eligible = (
        profile.principal_n >= 3
        and profile.outer_sp_electrons > profile.closed_shell_capacity / 2.0
    )

    degrees = [base]
    if eligible:
        degrees = list(range(base, dual + 1, 2))

    states = []
    for q, degree in enumerate(degrees):
        if q == 0:
            branch = "GROUND_NEAREST_CLOSED_SHELL"
            status = "FROZEN_BASE_RELATION_DEGREE"
        else:
            branch = "PAIR_REORGANIZATION_CANDIDATE"
            status = "MODEL_DEFINED_COORDINATION_REORGANIZATION_CANDIDATE"

        states.append(
            CoordinationState(
                Z=z,
                symbol=profile.symbol,
                q=q,
                relation_degree=degree,
                base_relation_degree=base,
                dual_relation_degree=dual,
                principal_n=profile.principal_n,
                outer_sp_electrons=profile.outer_sp_electrons,
                closed_shell_capacity=profile.closed_shell_capacity,
                branch=branch,
                status=status,
            )
        )
    return tuple(states)


def coordination_degrees(z: int) -> tuple[int, ...]:
    return tuple(state.relation_degree for state in coordination_ladder(z))


def monovalent_ligand_candidates(
    centre_z: int,
    ligand_z: int,
) -> tuple[MonovalentCoordinationCandidate, ...]:
    """Generate star-skeleton candidates for a degree-one ligand.

    The ligand must remain degree one under the frozen v0.1 shell rule.  The
    returned formulas are structural coordination candidates only; no stability,
    geometry, oxidation state, or bond energy is implied.
    """
    ligand = valence_shell_profile(ligand_z)
    if ligand.relation_degree != 1:
        raise ValueError("v0.5 monovalent ligand gate requires relation degree 1")

    centre_symbol = ELEMENT_SYMBOLS[centre_z]
    ligand_symbol = ELEMENT_SYMBOLS[ligand_z]
    out = []
    for state in coordination_ladder(centre_z):
        degree = state.relation_degree
        if degree <= 0:
            continue
        formula = centre_symbol + ligand_symbol + (str(degree) if degree != 1 else "")
        out.append(
            MonovalentCoordinationCandidate(
                centre_Z=centre_z,
                centre_symbol=centre_symbol,
                ligand_Z=ligand_z,
                ligand_symbol=ligand_symbol,
                q=state.q,
                centre_relation_degree=degree,
                ligand_count=degree,
                empirical_formula=formula,
            )
        )
    return tuple(out)
